### ISSUE TITLE
App crashes when removing two adjacent novels in library

### ISSUE THREAD

**Issue by codefionn** [gmathi/NovelLibrary#182]
If you first remove a novel and then remove the novel right below that one, the app crashes.

**Comment by codefionn** [comment]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.gmathi.novellibrary, PID: 6654
    java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.get(ArrayList.java:437)
        at io.github.gmathi.novellibrary.fragment.LibraryFragment$onItemDismiss$$inlined$let$lambda$1.invoke(LibraryFragment.kt:532)
        at io.github.gmathi.novellibrary.fragment.LibraryFragment$onItemDismiss$$inlined$let$lambda$1.invoke(LibraryFragment.kt:46)

The index of the novels of the view  model maybe are invalid after deleting some novels.

**Comment by gmathi** [comment]
Good find! Are you looking in to this? or should I make a fix.

**Comment by codefionn** [comment]
Today and tomorrow I try to fix this

**Comment by gmathi** [comment]
@codefionn I fixed this in 0.18 branch.

**Comment by codefionn** [comment]
Ohh, okay didn't read that
