### ISSUE TITLE
Startup Crash

### ISSUE THREAD

**Issue by mystfox** [gmathi/NovelLibrary#222]
I've somehow gotten into a state where the app closes immediately after opening, and even repeatedly launching isn't getting me an option to see crash details. From what I remember right before this happened, I accidentally did "Novel Details" instead of that I meant to do "assign novel category" (or whatever the exact term... the app won't open so I forget), I immediately do the back swipe, as it goes off I see a dialog or popup of some sort come up and immediately disappear, I think nothing of it, back again from the loading screen because I just don't want to be there, app... I believe I was just kicked back to launcher, as far as I can see. All that happens when trying to launch is the screen of a solid color, then I'm back to launcher. I can get the "keeps stopping" message, but no options for crash report - because it's not from Play store, idk?

Crash details from Scoop:
```
FATAL EXCEPTION: main
Process: io.github.gmathi.novellibrary, PID: 13316
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	... 1 more
Caused by: java.net.MalformedURLException: no protocol: /dist/img/nocover-new-min.png
	at java.net.URL.<init>(URL.java:601)
	at java.net.URL.<init>(URL.java:498)
	at java.net.URL.<init>(URL.java:447)
	at io.github.gmathi.novellibrary.util.lang.StringExtensionsKt.getGlideUrl(StringExtensions.kt:95)
	at io.github.gmathi.novellibrary.fragment.LibraryFragment.bind(LibraryFragment.kt:163)
	at io.github.gmathi.novellibrary.fragment.LibraryFragment.bind(LibraryFragment.kt:53)
	at io.github.gmathi.novellibrary.adapter.GenericAdapter$Listener$DefaultImpls.bind(GenericAdapter.kt:59)
	at io.github.gmathi.novellibrary.fragment.LibraryFragment.bind(LibraryFragment.kt:53)
	at io.github.gmathi.novellibrary.fragment.LibraryFragment.bind(LibraryFragment.kt:53)
	at io.github.gmathi.novellibrary.adapter.GenericAdapter$ViewHolder.bind(GenericAdapter.kt:48)
	at io.github.gmathi.novellibrary.adapter.GenericAdapter.onBindViewHolder(GenericAdapter.kt:28)
	at io.github.gmathi.novellibrary.adapter.GenericAdapter.onBindViewHolder(GenericAdapter.kt:13)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
	at android.view.View.layout(View.java:22844)
	at android.view.ViewGroup.layout(ViewGroup.java:6389)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
	at android.view.View.layout(View.java:22844)
	at android.view.ViewGroup.layout(ViewGroup.java:6389)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:22844)
	at android.view.ViewGroup.layout(ViewGroup.java:6389)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:22844)
	at android.view.ViewGroup.layout(ViewGroup.java:6389)
	at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
	at android.view.View.layout(View.java:22844)
	at android.view.ViewGroup.layout(ViewGroup.java:6389)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22844)
	at android.view.ViewGroup.layout(ViewGroup.java:6389)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2003)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
	at android.view.View.layout(View.java:22844)
	at android.view.ViewGroup.layout(ViewGroup.java:6389)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22844)
	at android.view.ViewGroup.layout(ViewGroup.java:6389)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
	at android.view.View.layout(View.java:22844)
	at android.view.ViewGroup.layout(ViewGroup.java:6389)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22844)
	at android.view.ViewGroup.layout(ViewGroup.java:6389)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22844)
	at android.view.ViewGroup.layout(ViewGroup.java:6389)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22844)
	at android.view.ViewGroup.layout(ViewGroup.java:6389)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22844)
	at android.view.ViewGroup.layout(ViewGroup.java:6389)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:784)
	at android.view.View.layout(View.java:22844)
	at android.view.ViewGroup.layout(ViewGroup.java:6389)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3475)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2943)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1948)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8177)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:731)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	... 3 more
```

**Comment by gmathi** [comment]
Thanks for this. I will look into this.
